--------------------------------------------------------
--  DDL for Table PREDMETY
--------------------------------------------------------

  CREATE TABLE "ST55409"."PREDMETY" 
   (	"ID_PREDMETU" NUMBER(*,0), 
	"ZKRATKA" CHAR(60 BYTE), 
	"NAZEV" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table ZPRAVY
--------------------------------------------------------

  CREATE TABLE "ST55409"."ZPRAVY" 
   (	"ID_ZPRAVY" NUMBER(*,0), 
	"CASOVE_RAZITKO" TIMESTAMP (6), 
	"OBSAH" CLOB, 
	"POZNAMKA" VARCHAR2(120 BYTE), 
	"PREDMET" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" 
 LOB ("OBSAH") STORE AS SECUREFILE (
  TABLESPACE "STUDENTI" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table UZIVATELE_SP
--------------------------------------------------------

  CREATE TABLE "ST55409"."UZIVATELE_SP" 
   (	"ID_UZIVATELE_SP" NUMBER(6,0), 
	"ID_UZIVATELE" NUMBER(6,0), 
	"ID_ST_PLANU" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table UZIVATELE
--------------------------------------------------------

  CREATE TABLE "ST55409"."UZIVATELE" 
   (	"ID_UZIVATELE" NUMBER(10,0), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"HESLO" VARCHAR2(20 BYTE), 
	"JMENO" VARCHAR2(20 BYTE), 
	"PRIJMENI" VARCHAR2(20 BYTE), 
	"POZNAMKA" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"BLOKACE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table ZAPOCTY
--------------------------------------------------------

  CREATE TABLE "ST55409"."ZAPOCTY" 
   (	"ID_ZAPOCTU" NUMBER(*,0), 
	"CASOVE_RAZITKO" TIMESTAMP (6), 
	"STAV" NUMBER(*,0), 
	"ID_PREDMETU" NUMBER(*,0), 
	"ID_UZIVATELE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table UDALOSTI
--------------------------------------------------------

  CREATE TABLE "ST55409"."UDALOSTI" 
   (	"ID_UDALOSTI" NUMBER(6,0), 
	"DATUM" TIMESTAMP (6), 
	"OBSAH" CLOB, 
	"NAZEV" VARCHAR2(20 BYTE), 
	"ID_UZIVATELE" NUMBER(6,0), 
	"MISTO_KONANI" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" 
 LOB ("OBSAH") STORE AS SECUREFILE (
  TABLESPACE "STUDENTI" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table STUDIJNI_PLANY
--------------------------------------------------------

  CREATE TABLE "ST55409"."STUDIJNI_PLANY" 
   (	"ID_PLANU" NUMBER(*,0), 
	"NAZEV" VARCHAR2(120 BYTE), 
	"ID_OBORU" NUMBER(*,0), 
	"POPIS" VARCHAR2(260 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table STUDIJNI_OBORY
--------------------------------------------------------

  CREATE TABLE "ST55409"."STUDIJNI_OBORY" 
   (	"ID_OBORU" NUMBER(*,0), 
	"NAZEV" VARCHAR2(255 BYTE), 
	"POPIS" VARCHAR2(550 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table STAV_SPLNENI_PODMINEK
--------------------------------------------------------

  CREATE TABLE "ST55409"."STAV_SPLNENI_PODMINEK" 
   (	"ID_STAV_PD" NUMBER(*,0), 
	"STATUS" NUMBER(*,0), 
	"ID_ZAPOCTU" NUMBER(*,0), 
	"ID_PODMINKY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table SKUPINY_PREDMETY
--------------------------------------------------------

  CREATE TABLE "ST55409"."SKUPINY_PREDMETY" 
   (	"ID_SKUPINY" NUMBER, 
	"ID_PREDMETU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table SKUPINY
--------------------------------------------------------

  CREATE TABLE "ST55409"."SKUPINY" 
   (	"ID_SKUPINY" NUMBER(6,0), 
	"NAZEV" VARCHAR2(30 BYTE), 
	"ID_KOMENTARE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table SKUPINA_CLENY
--------------------------------------------------------

  CREATE TABLE "ST55409"."SKUPINA_CLENY" 
   (	"ID_SKUPINY" NUMBER(*,0), 
	"ID_UZIVATELE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table ROLE_UZIVATELE
--------------------------------------------------------

  CREATE TABLE "ST55409"."ROLE_UZIVATELE" 
   (	"ID_ROLE_UZIVATELE" NUMBER(6,0), 
	"ID_ROLE" NUMBER, 
	"ID_UZIVATELE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table PREDMETY_VYUCUJICI
--------------------------------------------------------

  CREATE TABLE "ST55409"."PREDMETY_VYUCUJICI" 
   (	"ID_PREDMETU" NUMBER(*,0), 
	"ID_VYUCUJICIHO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "ST55409"."ROLE" 
   (	"ID_ROLE" NUMBER(*,0), 
	"NAZEV" VARCHAR2(20 BYTE), 
	"POZNAMKA" VARCHAR2(30 BYTE), 
	"OPRAVNENI" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table PREDMETY_SP
--------------------------------------------------------

  CREATE TABLE "ST55409"."PREDMETY_SP" 
   (	"ID_PREDMETU_SP" NUMBER(6,0), 
	"ID_PLANU" NUMBER(6,0), 
	"ID_PREDMETU" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table PODMINKY_PREDMETY
--------------------------------------------------------

  CREATE TABLE "ST55409"."PODMINKY_PREDMETY" 
   (	"ID_PREDMETU" NUMBER(*,0), 
	"ID_PODMINKY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table PODMINKY_ZAPOCTY
--------------------------------------------------------

  CREATE TABLE "ST55409"."PODMINKY_ZAPOCTY" 
   (	"ID_PODMINKY" NUMBER(*,0), 
	"POPIS" VARCHAR2(360 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table OZNAMENI_ZMENA
--------------------------------------------------------

  CREATE TABLE "ST55409"."OZNAMENI_ZMENA" 
   (	"ID" NUMBER(*,0), 
	"NOTIFICATION_OBJECT_ID" NUMBER(*,0), 
	"ACTOR_ID" NUMBER(*,0), 
	"STATUS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table OZNAMENI
--------------------------------------------------------

  CREATE TABLE "ST55409"."OZNAMENI" 
   (	"ID" NUMBER(*,0), 
	"NOTIFICATION_OBJECT_ID" NUMBER(*,0), 
	"NOTIFIER_ID" NUMBER(*,0), 
	"STATUS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table LIKES
--------------------------------------------------------

  CREATE TABLE "ST55409"."LIKES" 
   (	"ID" NUMBER(*,0), 
	"DATETIME" TIMESTAMP (6), 
	"OBRAZEK_ID" NUMBER(*,0), 
	"POST_ID" NUMBER(*,0), 
	"ID_UZIVATELE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table KORESPONDENCE
--------------------------------------------------------

  CREATE TABLE "ST55409"."KORESPONDENCE" 
   (	"ID_KORESPONDENCE" NUMBER(6,0), 
	"ID_ODESILATEL" NUMBER(6,0), 
	"ID_ZPRAVY" NUMBER(6,0), 
	"ID_ADRESAT" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table KOMENTARE
--------------------------------------------------------

  CREATE TABLE "ST55409"."KOMENTARE" 
   (	"ID_KOMENTARE" NUMBER(6,0), 
	"DATUM" TIMESTAMP (6), 
	"OBSAH" CLOB, 
	"ID_PODKOMENTARE" NUMBER, 
	"BLOKACE" NUMBER, 
	"NAZEV" VARCHAR2(255 CHAR), 
	"ID_UZIVATELE" NUMBER(10,0), 
	"ID_OBRAZKU" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" 
 LOB ("OBSAH") STORE AS SECUREFILE (
  TABLESPACE "STUDENTI" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table IMAGES
--------------------------------------------------------

  CREATE TABLE "ST55409"."IMAGES" 
   (	"IMAGE" BLOB, 
	"NAME" VARCHAR2(200 CHAR), 
	"ID" NUMBER, 
	"CAS" TIMESTAMP (6), 
	"POPISEK" VARCHAR2(150 CHAR), 
	"ID_UZIV" NUMBER(*,0), 
	"DEFAULT_PC" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" 
 LOB ("IMAGE") STORE AS SECUREFILE (
  TABLESPACE "STUDENTI" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FRIENDS
--------------------------------------------------------

  CREATE TABLE "ST55409"."FRIENDS" 
   (	"ID_UZIVATELE1" NUMBER(*,0), 
	"ID_UZIVATELE2" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table ENTITA_OZNAMENI
--------------------------------------------------------

  CREATE TABLE "ST55409"."ENTITA_OZNAMENI" 
   (	"ID" NUMBER(*,0), 
	"NAZEV" VARCHAR2(60 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table OBJEKT_OZNAMENI
--------------------------------------------------------

  CREATE TABLE "ST55409"."OBJEKT_OZNAMENI" 
   (	"ID" NUMBER(*,0), 
	"ENTITY_TYPE" NUMBER(*,0), 
	"ENTITY_ID" NUMBER(*,0), 
	"CREATED_ON" TIMESTAMP (6), 
	"STATUS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0041965
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0041965" ON "ST55409"."PREDMETY" ("ID_PREDMETU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0041982
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0041982" ON "ST55409"."ZPRAVY" ("ID_ZPRAVY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0041991
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0041991" ON "ST55409"."UZIVATELE_SP" ("ID_UZIVATELE_SP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0038890
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0038890" ON "ST55409"."UZIVATELE" ("ID_UZIVATELE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index UZIVATEL_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."UZIVATEL_UNIQUE" ON "ST55409"."UZIVATELE" ("LOGIN", "HESLO", "EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index UZIV_JMENO__2
--------------------------------------------------------

  CREATE BITMAP INDEX "ST55409"."UZIV_JMENO__2" ON "ST55409"."UZIVATELE" ("PRIJMENI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index ZAPOCET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."ZAPOCET_PK" ON "ST55409"."ZAPOCTY" ("ID_ZAPOCTU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0041978
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0041978" ON "ST55409"."STUDIJNI_PLANY" ("ID_PLANU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0041972
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0041972" ON "ST55409"."STUDIJNI_OBORY" ("ID_OBORU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index STAV_SPLNENI_PODMINEK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."STAV_SPLNENI_PODMINEK_PK" ON "ST55409"."STAV_SPLNENI_PODMINEK" ("ID_STAV_PD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C00136583
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C00136583" ON "ST55409"."SKUPINY_PREDMETY" ("ID_SKUPINY", "ID_PREDMETU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0042019
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0042019" ON "ST55409"."SKUPINY" ("ID_SKUPINY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SKUPINY_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SKUPINY_UNIQUE" ON "ST55409"."SKUPINY" ("NAZEV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C00135610
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C00135610" ON "ST55409"."SKUPINA_CLENY" ("ID_SKUPINY", "ID_UZIVATELE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0041997
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0041997" ON "ST55409"."ROLE_UZIVATELE" ("ID_ROLE_UZIVATELE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C00135630
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C00135630" ON "ST55409"."PREDMETY_VYUCUJICI" ("ID_PREDMETU", "ID_VYUCUJICIHO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0041968
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0041968" ON "ST55409"."ROLE" ("ID_ROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0042024
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0042024" ON "ST55409"."PREDMETY_SP" ("ID_PREDMETU_SP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index PREDMETY_SP_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."PREDMETY_SP_UNIQUE" ON "ST55409"."PREDMETY_SP" ("ID_PLANU", "ID_PREDMETU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index PODMINKY_ZAPOCTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."PODMINKY_ZAPOCTY_PK" ON "ST55409"."PODMINKY_ZAPOCTY" ("ID_PODMINKY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C00113442
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C00113442" ON "ST55409"."OZNAMENI_ZMENA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C00113436
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C00113436" ON "ST55409"."OZNAMENI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index LIKE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."LIKE_PK" ON "ST55409"."LIKES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0042003
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0042003" ON "ST55409"."KORESPONDENCE" ("ID_KORESPONDENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index KOMENTARE_ID_
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."KOMENTARE_ID_" ON "ST55409"."KOMENTARE" ("ID_KOMENTARE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index IMAGES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."IMAGES_PK" ON "ST55409"."IMAGES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index PK_FRIENDS_USERID1_USERID2
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."PK_FRIENDS_USERID1_USERID2" ON "ST55409"."FRIENDS" ("ID_UZIVATELE1", "ID_UZIVATELE2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C00127587
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C00127587" ON "ST55409"."ENTITA_OZNAMENI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C00113427
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C00113427" ON "ST55409"."OBJEKT_OZNAMENI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Trigger DELETE_PREDMET
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ST55409"."DELETE_PREDMET" 
before delete on predmety
FOR EACH ROW
DECLARE 
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
delete from predmety_vyucujici pred_vuyc
where pred_vuyc.id_predmetu = :OLD.id_predmetu;
delete from predmety_sp psp
where psp.id_predmetu = :OLD.id_predmetu;
COMMIT;
END;
/
ALTER TRIGGER "ST55409"."DELETE_PREDMET" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_DELETE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ST55409"."USER_DELETE" 
BEFORE DELETE ON UZIVATELE
FOR EACH ROW 
DECLARE 
PRAGMA AUTONOMOUS_TRANSACTION;
CURSOR cur_1 
IS
SELECT id_role from ROLE_UZIVATELE
WHERE ROLE_UZIVATELE.ID_UZIVATELE = :OLD.ID_UZIVATELE AND ID_ROLE = 88;
v_role_uz  cur_1%ROWTYPE;
BEGIN
DELETE FROM UDALOSTI UD
WHERE UD.ID_UZIVATELE = :OLD.ID_UZIVATELE;
DELETE FROM IMAGES IM
WHERE IM.ID_UZIV = :OLD.ID_UZIVATELE;
DELETE FROM UZIVATELE_SP UZ_SP
WHERE UZ_SP.ID_UZIVATELE = :OLD.ID_UZIVATELE;
DELETE FROM ROLE_UZIVATELE R_UZ
WHERE R_UZ.ID_UZIVATELE = :OLD.ID_UZIVATELE;
BEGIN 
OPEN cur_1;
LOOP
FETCH cur_1 INTO v_role_uz;
IF cur_1%NOTFOUND  then
DBMS_OUTPUT.PUT_LINE('Nothing to deleete');
EXIT;
ELSE 
DELETE from SKUPINA_CLENY SK_CL
WHERE SK_CL.ID_UZIVATELE = :OLD.ID_UZIVATELE;
END IF;
END LOOP;
CLOSE cur_1;
END;
COMMIT;
END;
/
ALTER TRIGGER "ST55409"."USER_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ON_DELETE_GROUP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ST55409"."ON_DELETE_GROUP" 
before delete on skupiny
FOR EACH ROW 
DECLARE 
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
delete from skupina_cleny sk_cl 
where sk_cl.id_skupiny =:OLD.id_skupiny;
delete from skupiny_predmety psp
where psp.ID_SKUPINY = :OLD.id_skupiny;
COMMIT;
END;
/
ALTER TRIGGER "ST55409"."ON_DELETE_GROUP" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DELETE_GROUP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ST55409"."DELETE_GROUP" before
  DELETE ON skupiny FOR EACH ROW DECLARE PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    DELETE FROM skupina_cleny sk_cl WHERE sk_cl.id_skupiny =:OLD.id_skupiny;
    DELETE FROM SKUPINY_PREDMETY psp WHERE psp.ID_SKUPINY = :OLD.id_skupiny;
    COMMIT;
  END;
/
ALTER TRIGGER "ST55409"."DELETE_GROUP" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUDIT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ST55409"."AUDIT_TRIGGER" 
before insert or delete on friends
for each row
DECLARE 
v_transaction VARCHAR2(10); 
BEGIN
v_transaction := case
when updating then 'update'
when deleting then 'delete'
END;
INSERT INTO audits (table_name, transaction_name, by_user, transaction_date)
   VALUES('CUSTOMERS', v_transaction, USER, SYSDATE);
END;
/
ALTER TRIGGER "ST55409"."AUDIT_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table PREDMETY
--------------------------------------------------------

  ALTER TABLE "ST55409"."PREDMETY" MODIFY ("ID_PREDMETU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."PREDMETY" MODIFY ("ZKRATKA" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."PREDMETY" MODIFY ("NAZEV" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."PREDMETY" ADD PRIMARY KEY ("ID_PREDMETU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZPRAVY
--------------------------------------------------------

  ALTER TABLE "ST55409"."ZPRAVY" MODIFY ("ID_ZPRAVY" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ZPRAVY" MODIFY ("CASOVE_RAZITKO" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ZPRAVY" MODIFY ("OBSAH" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ZPRAVY" ADD PRIMARY KEY ("ID_ZPRAVY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
  ALTER TABLE "ST55409"."ZPRAVY" MODIFY ("PREDMET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UZIVATELE_SP
--------------------------------------------------------

  ALTER TABLE "ST55409"."UZIVATELE_SP" MODIFY ("ID_UZIVATELE_SP" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UZIVATELE_SP" MODIFY ("ID_UZIVATELE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UZIVATELE_SP" MODIFY ("ID_ST_PLANU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UZIVATELE_SP" ADD PRIMARY KEY ("ID_UZIVATELE_SP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UZIVATELE
--------------------------------------------------------

  ALTER TABLE "ST55409"."UZIVATELE" ADD CONSTRAINT "UZIVATEL_UNIQUE" UNIQUE ("LOGIN", "HESLO", "EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
  ALTER TABLE "ST55409"."UZIVATELE" MODIFY ("ID_UZIVATELE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UZIVATELE" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UZIVATELE" ADD PRIMARY KEY ("ID_UZIVATELE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZAPOCTY
--------------------------------------------------------

  ALTER TABLE "ST55409"."ZAPOCTY" MODIFY ("ID_UZIVATELE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ZAPOCTY" MODIFY ("ID_ZAPOCTU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ZAPOCTY" MODIFY ("CASOVE_RAZITKO" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ZAPOCTY" MODIFY ("STAV" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ZAPOCTY" MODIFY ("ID_PREDMETU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ZAPOCTY" ADD CONSTRAINT "ZAPOCET_PK" PRIMARY KEY ("ID_ZAPOCTU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UDALOSTI
--------------------------------------------------------

  ALTER TABLE "ST55409"."UDALOSTI" MODIFY ("ID_UDALOSTI" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UDALOSTI" MODIFY ("DATUM" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UDALOSTI" MODIFY ("OBSAH" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UDALOSTI" MODIFY ("NAZEV" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UDALOSTI" MODIFY ("ID_UZIVATELE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDIJNI_PLANY
--------------------------------------------------------

  ALTER TABLE "ST55409"."STUDIJNI_PLANY" MODIFY ("ID_PLANU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."STUDIJNI_PLANY" MODIFY ("NAZEV" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."STUDIJNI_PLANY" MODIFY ("ID_OBORU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."STUDIJNI_PLANY" ADD PRIMARY KEY ("ID_PLANU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDIJNI_OBORY
--------------------------------------------------------

  ALTER TABLE "ST55409"."STUDIJNI_OBORY" MODIFY ("ID_OBORU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."STUDIJNI_OBORY" MODIFY ("NAZEV" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."STUDIJNI_OBORY" ADD PRIMARY KEY ("ID_OBORU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAV_SPLNENI_PODMINEK
--------------------------------------------------------

  ALTER TABLE "ST55409"."STAV_SPLNENI_PODMINEK" MODIFY ("ID_STAV_PD" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."STAV_SPLNENI_PODMINEK" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."STAV_SPLNENI_PODMINEK" MODIFY ("ID_ZAPOCTU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."STAV_SPLNENI_PODMINEK" MODIFY ("ID_PODMINKY" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."STAV_SPLNENI_PODMINEK" ADD CONSTRAINT "STAV_SPLNENI_PODMINEK_PK" PRIMARY KEY ("ID_STAV_PD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKUPINY_PREDMETY
--------------------------------------------------------

  ALTER TABLE "ST55409"."SKUPINY_PREDMETY" MODIFY ("ID_SKUPINY" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."SKUPINY_PREDMETY" MODIFY ("ID_PREDMETU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."SKUPINY_PREDMETY" ADD PRIMARY KEY ("ID_SKUPINY", "ID_PREDMETU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKUPINY
--------------------------------------------------------

  ALTER TABLE "ST55409"."SKUPINY" MODIFY ("ID_SKUPINY" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."SKUPINY" MODIFY ("NAZEV" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."SKUPINY" ADD PRIMARY KEY ("ID_SKUPINY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
  ALTER TABLE "ST55409"."SKUPINY" ADD CONSTRAINT "SKUPINY_UNIQUE" UNIQUE ("NAZEV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKUPINA_CLENY
--------------------------------------------------------

  ALTER TABLE "ST55409"."SKUPINA_CLENY" MODIFY ("ID_SKUPINY" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."SKUPINA_CLENY" MODIFY ("ID_UZIVATELE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."SKUPINA_CLENY" ADD PRIMARY KEY ("ID_SKUPINY", "ID_UZIVATELE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE_UZIVATELE
--------------------------------------------------------

  ALTER TABLE "ST55409"."ROLE_UZIVATELE" MODIFY ("ID_ROLE_UZIVATELE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ROLE_UZIVATELE" MODIFY ("ID_ROLE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ROLE_UZIVATELE" MODIFY ("ID_UZIVATELE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ROLE_UZIVATELE" ADD PRIMARY KEY ("ID_ROLE_UZIVATELE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PREDMETY_VYUCUJICI
--------------------------------------------------------

  ALTER TABLE "ST55409"."PREDMETY_VYUCUJICI" MODIFY ("ID_PREDMETU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."PREDMETY_VYUCUJICI" ADD PRIMARY KEY ("ID_PREDMETU", "ID_VYUCUJICIHO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "ST55409"."ROLE" MODIFY ("ID_ROLE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ROLE" MODIFY ("NAZEV" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ROLE" ADD PRIMARY KEY ("ID_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PREDMETY_SP
--------------------------------------------------------

  ALTER TABLE "ST55409"."PREDMETY_SP" MODIFY ("ID_PREDMETU_SP" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."PREDMETY_SP" MODIFY ("ID_PLANU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."PREDMETY_SP" MODIFY ("ID_PREDMETU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."PREDMETY_SP" ADD PRIMARY KEY ("ID_PREDMETU_SP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
  ALTER TABLE "ST55409"."PREDMETY_SP" ADD CONSTRAINT "PREDMETY_SP_UNIQUE" UNIQUE ("ID_PLANU", "ID_PREDMETU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PODMINKY_PREDMETY
--------------------------------------------------------

  ALTER TABLE "ST55409"."PODMINKY_PREDMETY" MODIFY ("ID_PREDMETU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."PODMINKY_PREDMETY" MODIFY ("ID_PODMINKY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PODMINKY_ZAPOCTY
--------------------------------------------------------

  ALTER TABLE "ST55409"."PODMINKY_ZAPOCTY" MODIFY ("ID_PODMINKY" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."PODMINKY_ZAPOCTY" MODIFY ("POPIS" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."PODMINKY_ZAPOCTY" ADD CONSTRAINT "PODMINKY_ZAPOCTY_PK" PRIMARY KEY ("ID_PODMINKY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OZNAMENI_ZMENA
--------------------------------------------------------

  ALTER TABLE "ST55409"."OZNAMENI_ZMENA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."OZNAMENI_ZMENA" MODIFY ("NOTIFICATION_OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."OZNAMENI_ZMENA" MODIFY ("ACTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."OZNAMENI_ZMENA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
  ALTER TABLE "ST55409"."OZNAMENI_ZMENA" MODIFY ("STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OZNAMENI
--------------------------------------------------------

  ALTER TABLE "ST55409"."OZNAMENI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."OZNAMENI" MODIFY ("NOTIFICATION_OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."OZNAMENI" MODIFY ("NOTIFIER_ID" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."OZNAMENI" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."OZNAMENI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIKES
--------------------------------------------------------

  ALTER TABLE "ST55409"."LIKES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."LIKES" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."LIKES" ADD CONSTRAINT "LIKE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KORESPONDENCE
--------------------------------------------------------

  ALTER TABLE "ST55409"."KORESPONDENCE" MODIFY ("ID_KORESPONDENCE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."KORESPONDENCE" MODIFY ("ID_ODESILATEL" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."KORESPONDENCE" MODIFY ("ID_ZPRAVY" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."KORESPONDENCE" ADD PRIMARY KEY ("ID_KORESPONDENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
  ALTER TABLE "ST55409"."KORESPONDENCE" MODIFY ("ID_ADRESAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KOMENTARE
--------------------------------------------------------

  ALTER TABLE "ST55409"."KOMENTARE" MODIFY ("BLOKACE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."KOMENTARE" MODIFY ("ID_KOMENTARE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."KOMENTARE" MODIFY ("DATUM" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."KOMENTARE" MODIFY ("OBSAH" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."KOMENTARE" ADD CONSTRAINT "KOMENTARE_ID_PK" PRIMARY KEY ("ID_KOMENTARE")
  USING INDEX (CREATE UNIQUE INDEX "ST55409"."KOMENTARE_ID_" ON "ST55409"."KOMENTARE" ("ID_KOMENTARE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" )  ENABLE;
  ALTER TABLE "ST55409"."KOMENTARE" MODIFY ("NAZEV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMAGES
--------------------------------------------------------

  ALTER TABLE "ST55409"."IMAGES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."IMAGES" ADD CONSTRAINT "IMAGES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
  ALTER TABLE "ST55409"."IMAGES" MODIFY ("IMAGE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."IMAGES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."IMAGES" MODIFY ("DEFAULT_PC" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."IMAGES" MODIFY ("ID_UZIV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FRIENDS
--------------------------------------------------------

  ALTER TABLE "ST55409"."FRIENDS" MODIFY ("ID_UZIVATELE1" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."FRIENDS" MODIFY ("ID_UZIVATELE2" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."FRIENDS" ADD CONSTRAINT "PK_FRIENDS_USERID1_USERID2" PRIMARY KEY ("ID_UZIVATELE1", "ID_UZIVATELE2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENTITA_OZNAMENI
--------------------------------------------------------

  ALTER TABLE "ST55409"."ENTITA_OZNAMENI" MODIFY ("NAZEV" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ENTITA_OZNAMENI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OBJEKT_OZNAMENI
--------------------------------------------------------

  ALTER TABLE "ST55409"."OBJEKT_OZNAMENI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."OBJEKT_OZNAMENI" MODIFY ("ENTITY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."OBJEKT_OZNAMENI" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."OBJEKT_OZNAMENI" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."OBJEKT_OZNAMENI" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."OBJEKT_OZNAMENI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
  
  
  
  
  --------------------------------------------------------
--  DDL for Procedure ADD_UPDATE_GROUP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ST55409"."ADD_UPDATE_GROUP" (id_sk in number,
nazev in varchar2, id_kom in number, id_predmetu in number, res out clob)
AS
v_plan number :=0;
v_id_skupiny number;
Begin
Select pr_sp.id_planu into v_plan from predmety_sp pr_sp
where pr_sp.id_predmetu = id_predmetu;
if v_plan = 0 then
res:= 'Predmet nema plan';
ELSIF id_sk is NULL then 
v_id_skupiny := SKUPINY_SQ.NEXTVAL;
insert into skupiny values(v_id_skupiny,nazev,id_kom);
INSERT INTO SKUPINY_PREDMETY VALUES(v_id_skupiny,id_predmetu);
else
insert into skupiny_predmety values(id_sk,id_predmetu);
end if;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_FIRENDSHIP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ST55409"."UPDATE_FIRENDSHIP" (uz1 in number,uz2 in number)
AS
BEGIN
INSERT INTO FRIENDS VALUES(uz1,uz2);
INSERT INTO FRIENDS VALUES(uz2,uz1);
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_FOTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ST55409"."UPDATE_FOTO" (image in blob,id_img out number,nazev in varchar2, popisek in varchar2,id_uziv in number, default_pc in 
number)
IS
BEGIN 
IF id_img is null then
id_img :=IMAGES_SQ.NEXTVAL;
insert into images values(image,nazev,id_img,SYSDATE,popisek,id_uziv,default_pc);
commit;
ELSE
UPDATE IMAGES SET cas =  sysdate
where id = id_img;
commit;
end if;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.put_line('Wrong image id');
ROLLBACK;
end update_foto;

/
--------------------------------------------------------
--  DDL for Procedure USER_LOGIN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ST55409"."USER_LOGIN" (p_login IN VARCHAR2, p_password IN VARCHAR2,p_result OUT INTEGER)
IS
CURSOR USER_CUR IS
SELECT login,heslo,id_uzivatele 
from uzivatele  
where login = p_login and heslo = p_password;
BEGIN
for cur in USER_CUR
LOOP
if USER_CUR%NOTFOUND THEN
p_result := -1;
EXIT;
ELSif cur.login = p_login AND cur.heslo = p_password then
p_result := cur.id_uzivatele;
else
p_result :=-2;
end if;
end loop;
EXCEPTION
WHEN NO_DATA_FOUND THEN
p_result:= -3;
end;

/








--------------------------------------------------------
--  DDL for Function ADD_UPDATE_USER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "ST55409"."ADD_UPDATE_USER" (id_uziv in integer,jmeno in VARCHAR2,login in VARCHAR2,prijmeni in VARCHAR2,
heslo in VARCHAR2,email in VARCHAR2) RETURN INTEGER
IS 
v_result INTEGER;
BEGIN
IF id_uziv IS NULL  THEN
v_result:= UZIV_ID_SQ.NEXTVAL;
insert into UZIVATELE VALUES(v_result,login, heslo,jmeno, prijmeni,' ',email,1);
ELSE 
UPDATE UZIVATELE uz
SET uz.jmeno = jmeno where id_uzivatele = id_uziv; 
UPDATE UZIVATELE uz
SET uz.prijmeni = jmeno where id_uzivatele = id_uziv; 
UPDATE UZIVATELE uz
SET uz.email = jmeno where id_uzivatele = id_uziv; 
UPDATE UZIVATELE uz
SET uz.login = jmeno where id_uzivatele = id_uziv; 
END IF;
COMMIT;
return v_result;
EXCEPTION
WHEN NO_DATA_FOUND THEN
raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
ROLLBACK ;
RETURN -1;
WHEN OTHERS THEN
raise_application_error(-20002,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
ROLLBACK;
RETURN -2;
END;

/
--------------------------------------------------------
--  DDL for Function AREFRIENDS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "ST55409"."AREFRIENDS" (user1 IN INTEGER, user2 IN INTEGER)
RETURN INTEGER
IS

v_friends  INTEGER :=0;

CURSOR c_cursor
IS
SELECT oz.notifier_id,ozn_zm.actor_id,obk_ozn.id
from objekt_oznameni obk_ozn
inner join oznameni oz on oz.notification_object_id = obk_ozn.id
inner join oznameni_zmena ozn_zm  on ozn_zm.notification_object_id = obk_ozn.id
WHERE obk_ozn.entity_type = 4;
v_cursor c_cursor%ROWTYPE;
BEGIN
OPEN c_cursor;
LOOP
FETCH c_cursor INTO  v_cursor;
IF c_cursor%NOTFOUND THEN
EXIT;
ELSIF v_cursor.notifier_id = user1 AND v_cursor.actor_id = user2 THEN
v_friends := 1;
return v_friends;
ELSIF v_cursor.notifier_id = user2 AND v_cursor.actor_id = user1 THEN
v_friends := 1;
return v_friends;
END IF;
END LOOP;
CLOSE c_cursor;
return v_friends;
END; 

/
--------------------------------------------------------
--  DDL for Function ISUSERBLOCKED
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "ST55409"."ISUSERBLOCKED" (
    id_uz IN INTEGER)
  RETURN INTEGER
IS
  v_blokace INTEGER:= 1;
BEGIN
  SELECT blokace INTO v_blokace FROM UZIVATELE WHERE ID_UZIVATELE = id_uz;
  RETURN v_blokace;
END isUserBlocked;

/






--------------------------------------------------------
--  DDL for Trigger DELETE_GROUP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ST55409"."DELETE_GROUP" before
  DELETE ON skupiny FOR EACH ROW DECLARE PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    DELETE FROM skupina_cleny sk_cl WHERE sk_cl.id_skupiny =:OLD.id_skupiny;
    DELETE FROM SKUPINY_PREDMETY psp WHERE psp.ID_SKUPINY = :OLD.id_skupiny;
    COMMIT;
  END;
/
ALTER TRIGGER "ST55409"."DELETE_GROUP" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DELETE_PREDMET
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ST55409"."DELETE_PREDMET" 
before delete on predmety
FOR EACH ROW
DECLARE 
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
delete from predmety_vyucujici pred_vuyc
where pred_vuyc.id_predmetu = :OLD.id_predmetu;
delete from predmety_sp psp
where psp.id_predmetu = :OLD.id_predmetu;
COMMIT;
END;
/
ALTER TRIGGER "ST55409"."DELETE_PREDMET" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_DELETE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ST55409"."USER_DELETE" 
BEFORE DELETE ON UZIVATELE
FOR EACH ROW 
DECLARE 
PRAGMA AUTONOMOUS_TRANSACTION;
CURSOR cur_1 
IS
SELECT id_role from ROLE_UZIVATELE
WHERE ROLE_UZIVATELE.ID_UZIVATELE = :OLD.ID_UZIVATELE AND ID_ROLE = 88;
v_role_uz  cur_1%ROWTYPE;
BEGIN
DELETE FROM UDALOSTI UD
WHERE UD.ID_UZIVATELE = :OLD.ID_UZIVATELE;
DELETE FROM IMAGES IM
WHERE IM.ID_UZIV = :OLD.ID_UZIVATELE;
DELETE FROM UZIVATELE_SP UZ_SP
WHERE UZ_SP.ID_UZIVATELE = :OLD.ID_UZIVATELE;
DELETE FROM ROLE_UZIVATELE R_UZ
WHERE R_UZ.ID_UZIVATELE = :OLD.ID_UZIVATELE;
BEGIN 
OPEN cur_1;
LOOP
FETCH cur_1 INTO v_role_uz;
IF cur_1%NOTFOUND  then
DBMS_OUTPUT.PUT_LINE('Nothing to deleete');
EXIT;
ELSE 
DELETE from SKUPINA_CLENY SK_CL
WHERE SK_CL.ID_UZIVATELE = :OLD.ID_UZIVATELE;
END IF;
END LOOP;
CLOSE cur_1;
END;
COMMIT;
END;
/
ALTER TRIGGER "ST55409"."USER_DELETE" ENABLE;
